### ISSUE TITLE
[request] Mount for SD card reader

### ISSUE THREAD

**Issue by jyp** [BladeScraper-Designs/Ender-3-All-in-One-Enclosure#3]
Is there any chance to add a mount (and opening in a panel, preferrably left) for an arduino-friendly SD card reader? Be it a micro-sd reader or a full-size one?

**Comment by BladeScraper-Designs** [comment]
I think the best option would be to get a 12864 display and use the SD card reader in it.  I'm not aware of any SD card readers you can just plug into a MKS mainboard, and it doesn't have a built in card slot.

**Comment by jyp** [comment]
You can, in fact, connect a catalex SD card reader to the mks aux 3 port --- and this is supported by Marlin with a 1-line modification. I have done this myself.
I've hacked together a case including this mount https://www.thingiverse.com/thing:2475109
I can't share it due to the license, but anyway it is a worse design than yours.

**Comment by BladeScraper-Designs** [comment]
I know I'm a bit late, but I decided to have a crack at something tonight.  It's uploaded to the GitHub under STL.  Do know it's completely untested because I don't have an SD Card reader to try it with, but it should work.  Let me know if you try it out and/or if you have issues with it.  There are also rendered photos in the Photos folder on GitHub.

https://smile.amazon.com/WINGONEER-reader-module-interface-conversion/dp/B06XHJJWNC/ref=sr_1_4?ie=UTF8&qid=1547362677&sr=8-4&keywords=arduino+sd+card+reader

**Comment by jyp** [comment]
Thaks for this! However I found that the best method is to have a separate mount for the SD reader (just printed one yesterday...), so that it's easier to access (plus the usual advantages of modularity).
