### ISSUE TITLE
Use bolts for securing boards?

### ISSUE THREAD

**Issue by jaredgrubb** [BladeScraper-Designs/Ender-3-All-in-One-Enclosure#5]
I was remixing [another enclosure](https://www.thingiverse.com/thing:3331060) before I found this one, and I absolutely love your approach and I think I'm going to try yours out.

However, I saw your comment about the screw holes ripping out and I'm curious if you would want to use bolts to secure them. For example, this is a picture of a mod I did in the above Thing where I modified two of the four screws to accept bolts to secure them (my initial print wouldn't thread at all on one of the screw holes and I didn't like how insecure it felt). I've [posted an image](https://imgur.com/a/wv6d7Qk) to explain what I mean.

**Comment by BladeScraper-Designs** [comment]
that might be possible, but I'm not sure that would be any less likely to be ripped off the bottom than a screw hole.

**Comment by jaredgrubb** [comment]
When yours ripped out, was it that the screw pulled loose from the plastic threads (the threads were the weak point) or the whole hole assembly detached from the rest of the part?

**Comment by BladeScraper-Designs** [comment]
The whole fileted standoff got ripped off the bottom

**Comment by pyromanci** [comment]
I'e been remixing this design in Fusion360  for my boards I use. I have not had a problem with i applied a modeled M3 x 0.5 in Fusion360. While the printer didn't print the threads exact (as i was using .3mm layer height with the stock .4mm nozzle size for testing). It did create them well enough for the screws to recut the threads without shearing the standoffs. 

It's been a while since i last used Inventor, but i recall a plugin that could cut modeled threads.

**Comment by jaredgrubb** [comment]
I'm trying this out and I ripped out two of the screw holes already. I should have mounted it before I had it all wired together ugh. :/ Thankfully two of them held ok, so I'm ok for now.

I'm definitely tempted to try to remix it to avoid using plastic for threading, but just a hole to secure to a bolt. Either the bolt could be embedded (as shown above), or I'm tempted to just add some recesses in the base. Is there any disadvantage to that?
